ALTER TABLE EMPLEADOSINGLETABLE DROP CONSTRAINT MPLDSNGLTABLEMPRSD
ALTER TABLE EMPLEADOSINGLETABLE DROP CONSTRAINT MPLADOSINGLETABLED
DROP TABLE PERSONASINGLETABLE
DROP TABLE EMPLEADOSINGLETABLE
DROP TABLE EMPRESASINGLETABLE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
